print("Hello Git")
print("Learning CI/CD from master and branch")
print("Hello Avanthika! Jenkins picked up my latest code.")
print("Working on login automation")
print("Learning GitHub branches")
print("Jenkins Poll SCM is working!")